GET http://localHost:1234/user/login/sebas/sebas

###
POST http://localHost:1234/user/register
Content-Type: application/json

    {
    "docUser": 8765347,
    "nameUser": "ayuda",
    "passUser": "no"
    }   


###
GET http://localHost:1234/task/get

###
GET http://localHost:1234/task/Sebastian

###
POST http://localHost:1234/task/save
Content-Type: application/json

{
    "docUser": 1052382113,
    "nameTask": "al fin",
    "descTask": "si mi chamos",
    "stateTask": 1,
    "cateTask": "personal"
}
