GET http://localHost:1234/user/login/sebas/sebas

###
POST http://localHost:1234/user/register
Content-Type: application/json

    {
    "docUser": 8765347,
    "nameUser": "ayuda",
    "passUser": "no"
    }   

###
GET http://localHost:1234/task/get/1052382113


###
GET http://localHost:1234/task/doc/d5bc02a1-d4de-11ee-aa49-ec8eb55104fd
###
GET http://localHost:1234/task/Sebastian

###
POST http://localHost:1234/task/save
Content-Type: application/json

{
    "numTask": 1,
    "docUser": 1052382113,
    "nameTask": "al ??",
    "descTask": "si mi chamos",
    "stateTask": 1,
    "cateTask": 2
}

###
GET http://localHost:1234/task/num/1052382113

###
PUT http://localHost:1234/task/update
Content-Type: application/json

{
    "idTask":"489ee854-d59b-11ee-aa49-ec8eb55104fd",
    "nameTask": "Actualizo desde aca",
    "descTask": "si mi chamos",
    "stateTask": 1,
    "cateTask": 2
}

###
DELETE http://localHost:1234/task/delete
Content-Type: application/json

{
    "idTask": "34098466-d5b4-11ee-aa49-ec8eb55104fd"
}
